/*
 * Emscripten Wrapper for MicroQuickJS Compiler
 *
 * Provides a C interface for compiling JavaScript to bytecode in the browser.
 * This is compiled to WebAssembly and called from JavaScript.
 */

#ifdef EMSCRIPTEN

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <emscripten.h>

#include "cutils.h"
#include "mquickjs.h"

// Forward declaration of js_stdlib (defined in stdlib_export.c)
extern const JSSTDLibraryDef js_stdlib;

// Maximum bytecode size (1MB should be plenty)
#define MAX_BYTECODE_SIZE (1024 * 1024)

// Global buffer for bytecode output
static uint8_t bytecode_buffer[MAX_BYTECODE_SIZE];
static size_t bytecode_size = 0;

// Error message buffer
static char error_message[1024];

/**
 * Compile JavaScript source to bytecode
 *
 * Follows the same pattern as mqjs.c's compile_file() but outputs to a buffer.
 *
 * @param source_code JavaScript source code (null-terminated)
 * @param source_len Length of source code
 * @param target_addr Target flash address for pre-relocation (unused, kept for API compat)
 * @param use_32bit Generate 32-bit bytecode for ESP32 target (only effective on 64-bit hosts)
 * @return Bytecode size on success, -1 on error
 */
EMSCRIPTEN_KEEPALIVE
int compile_js_to_bytecode(const char* source_code, size_t source_len,
                           uintptr_t target_addr, int use_32bit) {
    uint8_t mem_buf[128 * 1024]; // 128KB heap for compilation
    JSContext *ctx;
    JSValue val;
    union {
        JSBytecodeHeader hdr;
#if JSW == 8
        JSBytecodeHeader32 hdr32;
#endif
    } hdr_buf;
    const uint8_t *data_buf;
    uint32_t data_len;
    size_t hdr_len, total_size;

    (void)target_addr;  // Unused

    bytecode_size = 0;
    error_message[0] = '\0';

    printf("[WASM] compile_js_to_bytecode called: source_len=%zu, use_32bit=%d\n", source_len, use_32bit);

    /* When compiling to bytecode, the actual content of the stdlib does
       not matter because the generated bytecode does not depend on
       it. We still need it so that the atoms for the parsing are
       defined. The JSContext must be discarded once the compilation
       is done. */
    ctx = JS_NewContext2(mem_buf, sizeof(mem_buf), &js_stdlib, TRUE);

    /* Parse JavaScript source (compile without running) */
    val = JS_Parse(ctx, source_code, source_len, "<input>", 0);
    if (JS_IsException(val)) {
        JSValue exception = JS_GetException(ctx);
        JSCStringBuf buf;
        const char *str = JS_ToCString(ctx, exception, &buf);
        if (str) {
            snprintf(error_message, sizeof(error_message), "%s", str);
        } else {
            snprintf(error_message, sizeof(error_message), "Compilation failed");
        }
        JS_FreeContext(ctx);
        return -1;
    }

    /* Prepare bytecode for serialization - same pattern as mqjs.c */
#if JSW == 8
    if (use_32bit) {
        if (JS_PrepareBytecode64to32(ctx, &hdr_buf.hdr32, &data_buf, &data_len, val)) {
            snprintf(error_message, sizeof(error_message),
                     "Could not convert the bytecode from 64 to 32 bits");
            JS_FreeContext(ctx);
            return -1;
        }
        hdr_len = sizeof(JSBytecodeHeader32);
    } else
#endif
    {
        (void)use_32bit;  // Unused on 32-bit hosts
        JS_PrepareBytecode(ctx, &hdr_buf.hdr, &data_buf, &data_len, val);

        /* Relocate to base_addr=0 for position-independent output.
           update_atoms=FALSE since we're compiling to file, not running. */
        JS_RelocateBytecode2(ctx, &hdr_buf.hdr, (uint8_t *)data_buf, data_len, 0, FALSE);
        hdr_len = sizeof(JSBytecodeHeader);
    }

    total_size = hdr_len + data_len;

    printf("[WASM] Bytecode prepared: hdr_len=%zu, data_len=%u, total=%zu\n",
           hdr_len, data_len, total_size);

    if (total_size > MAX_BYTECODE_SIZE) {
        snprintf(error_message, sizeof(error_message),
                 "Bytecode too large: %zu bytes (max %d)", total_size, MAX_BYTECODE_SIZE);
        JS_FreeContext(ctx);
        return -1;
    }

    /* Copy header and data to output buffer */
    memcpy(bytecode_buffer, &hdr_buf, hdr_len);
    memcpy(bytecode_buffer + hdr_len, data_buf, data_len);

    bytecode_size = total_size;

    JS_FreeContext(ctx);

    printf("[WASM] Compilation successful: bytecode_size=%zu\n", bytecode_size);

    return (int)bytecode_size;
}

/**
 * Get pointer to compiled bytecode
 * Call after successful compile_js_to_bytecode()
 */
EMSCRIPTEN_KEEPALIVE
uint8_t* get_bytecode_buffer(void) {
    return bytecode_buffer;
}

/**
 * Get error message from last compilation
 */
EMSCRIPTEN_KEEPALIVE
const char* get_error_message(void) {
    return error_message;
}

/**
 * Get bytecode size from last compilation
 */
EMSCRIPTEN_KEEPALIVE
size_t get_bytecode_size(void) {
    return bytecode_size;
}

#endif // EMSCRIPTEN
